### ISSUE TITLE
In void-installer, after changing partition layout, filesystem creator sees old partitions until reboot

### ISSUE THREAD

**Issue by nyanpasu64** [void-linux/void-mklive#130] opened 2020-07-05 18:35 UTC
I tried installing `void-live-x86_64-20191109.iso` on an old computer with a mechanical drive. After running `void-installer`, I repartitioned /dev/sda using cfdisk, and tried to setup filesystems on the partitions. However the filesystem creator saw the old partition layout. This persisted even after restarting `void-installer` and was only fixed by rebooting.

One person told me I could run `sudo partprobe /dev/sd*`, but partprobe is not found on the live ISO.

**Comment by msiism** [comment] 2020-07-08 22:16
Hi there,

this looks like a duplicate of #98, doesn't it?

**Comment by nyanpasu64** [comment] 2020-07-08 22:34
I don't think that's the same issue. From scanning through the images, I think #98 describes how setting a filesystem for a partition doesn't change the filesystem displayed. The assumption is that the partition layout is not changing.

> As far as I can see, this is not actually a bug, but rather a design issue. The file system setup dialog generated by menu_filesystems() can't reflect the user's choices for the new installation simply because it gets the information it displays by looking up the actual partition and file system layout on the device.

In my case, I think I ran cfdisk, wrote partition layout to disk... and the filesystem selection didn't see the partitions until reboot. My bug is about the partition layout, not the filesystems displayed.

**Closed** 2023-05-21 01:25 UTC
Labels: installer
