### ISSUE TITLE
Latest Linux kernel still included in ISO despite -v option

### ISSUE THREAD

**Issue by absolutelynothinghere** [void-linux/void-mklive#307] opened 2023-01-06 16:23 UTC
I specify `-v linux5.15` yet the latest `linux` package is still downloaded and included in the ISO, when I would like to use the specified version only.

**Comment by paper42** [comment] 2023-01-06 18:28
Duplicate of #128, removing the default kernel would break base-system's dependencies.

**Closed** 2023-01-06 18:28 UTC
