### ISSUE TITLE
username is not in the sudoers file

### ISSUE THREAD

**Issue by johna23-lab** [void-linux/void-mklive#278] opened 2022-08-12 14:22 UTC
It's been a few weeks since I updated void-mklive all the installation goes fine, once installed and rebooted when I try to update or install a package with "sudo xbps..." or just type "sudo" it tells me that the user is not in the sudoers file.

I know that one of the solutions is to do 
su
visudo
and remove from the line the # "# %wheel ALL=(ALL:ALL) ALL" 

The question is how to do it automatically like the old installers?
Thanks!

**Comment by classabbyamp** [comment] 2022-08-12 16:32
nothing has changed with the sudoers generation in 5 years, and there have been [very few commits](https://github.com/void-linux/void-mklive/commits/master/installer.sh.in) to the installer since the last official images. Did you generate your own live image?

**Comment by johna23-lab** [comment] 2022-08-12 17:14
"nothing has changed with the sudoers generation in 5 years"
That's the strange

"Did you generate your own live image?" 
Yes, but i hapen too with anoher generated images like this one
https://voidbuilds.xyz/


"Did you select the wheel group when creating your user in the installer?"
By default is already selected

**Comment by paper42** [comment] 2022-08-12 19:20
I can reproduce this with a new base image, the user is in the wheel group, but sudoers is not edited to allow sudo for the wheel group.

**Comment by paper42** [comment] 2022-08-12 19:21
maybe this is fixed by #263

**Comment by hervyqa** [comment] 2022-08-13 01:29
> maybe this is fixed by #263

#263 was indeed used to solve this problem.

**Comment by classabbyamp** [comment] 2022-09-03 03:12
fixed in #263

**Closed by classabbyamp** 2022-09-03 03:12 UTC
Labels: bug, installer
