### ISSUE TITLE
EFI variables are not supported on this system

### ISSUE THREAD

**Issue by Jlll1** [void-linux/void-mklive#231] opened 2022-02-05 00:48 UTC
I've been trying to create a custom void iso for personal use, with no success. After goinf through the usual void-installer process, I get an error
`failed to install GRUB to /dev/nvme0n1!`
Couple last lines from tty8
```
Running grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=void_grub --recheck /dev/nvme0n1
Installing for x86_64-efi platform.
EFI variables are not supported on this system.
EFI variables are not supported on this system.
grub-install: error: efibootmgr failed to register the boot entry: No such file or directory.
```

I've tried running `build-x86-images.sh` and `release.sh`, and try installing void from these isos, with the same result.

Of course, installing void through the official iso works just fine.
Any ideas as to what can be the reason for this?

**Comment by paper42** [comment] 2022-02-05 01:03
Are you sure you are booting in EFI mode (not legacy)?

**Comment by hervyqa** [comment] 2022-02-05 01:08
> Are you sure you are booting in EFI mode (not legacy)?

My guess is like that.

@Jlll1, try checking with `efibootmgr`.

**Comment by Jlll1** [comment] 2022-02-05 01:20
I'm pretty sure I am booting off of efi, since legacy mode is disabled in bios. 

`efibootmgr` returns the same message: `EFI variables are not supported on this system`

Additional check I did was checking if `/sys/firmware/efi` exists and it does indeed exist.

**Comment by hervyqa** [comment] 2022-02-05 01:25
> `efibootmgr` returns the same message: `EFI variables are not supported on this system`

means now use legacy boot mode, not uefi. :)
If you use uefi, the output of `efibootmgr` will look like this.

```
~ efibootmgr
Timeout: 0 seconds
BootOrder: 0000,9999
Boot0000* Your OS
Boot9999* USB Drive (UEFI)
```

**Comment by Jlll1** [comment] 2022-02-05 01:32
Hmm. That is surprising, considering the fact that legacy support is disabled in my bios.

Would you by any chance have some ideas why the official iso correctly boots in efi, and the ones I made don't?

**Comment by hervyqa** [comment] 2022-02-05 01:43
Try checking `efibootmgr` on an official iso voidlinux, does it really support uefi on your machine?
Or the same as before (iso modification), EFI support is invalid.

**Comment by Jlll1** [comment] 2022-02-05 10:48
Yes, the official iso does boot in efi. Here's the output of `efibootmgr`

```
BootCurrent: 0000
Timeout: 0 seconds
BootOrder: 2001,2002,2003
...
```

**Comment by hervyqa** [comment] 2022-02-08 01:47
Ok. Maybe I know where the problem is.
I have tried making custom ISO with KDE, with the latest kernel `5.15.19_1`.

It turns out that in the latest kernel `linux5.15.19` does not support `CONFIG_EFI_VARS`, therefore EFI variables are not supported. Just like @Jlll1 tried it.

> Installing for x86_64-efi platform.
> EFI variables are not supported on this system.
> EFI variables are not supported on this system.

```
# EFI (Extensible Firmware Interface) Support
#
# CONFIG_EFI_VARS is not set
```
https://github.com/void-linux/void-packages/blob/422fc33c4dc4bfd08ce9cfe4c0050e8d01a826d3/srcpkgs/linux5.15/files/x86_64-dotconfig#L2194

While the official iso voidlinux 20210930 EFI succeeded, because at that time it used the kernel by activating EFI variables.

> Try checking efibootmgr on an official iso voidlinux, does it really support uefi on your machine?
> Yes, the official iso does boot in efi.

```
# EFI (Extensible Firmware Interface) Support
#
CONFIG_EFI_VARS=y
```
https://github.com/void-linux/void-packages/blob/422fc33c4dc4bfd08ce9cfe4c0050e8d01a826d3/srcpkgs/linux5.13/files/x86_64-dotconfig#L683

but I don't know the reason why `CONFIG_EFI_VARS` is not set.
cc @paper42 @ericonr @leahneukirchen

**Comment by hervyqa** [comment] 2022-02-08 02:26
I check again, `linux5.14` still activates `CONFIG_EFI_VARS=y`. while `linux5.15` hasn't.

```
#
# EFI (Extensible Firmware Interface) Support
#
CONFIG_EFI_VARS=y
```

https://github.com/void-linux/void-packages/blob/422fc33c4dc4bfd08ce9cfe4c0050e8d01a826d3/srcpkgs/linux5.14/files/x86_64-dotconfig#L685

**Comment by sgn** [comment] 2022-02-08 04:18
```
config EFI_VARS
	tristate "EFI Variable Support via sysfs"
	depends on EFI && (X86 || IA64)
	default n
	help
	  If you say Y here, you are able to get EFI (Extensible Firmware
	  Interface) variable information via sysfs.  You may read,
	  write, create, and destroy EFI variables through this interface.
	  Note that this driver is only retained for compatibility with
	  legacy users: new users should use the efivarfs filesystem
	  instead.
```
 `CONFIG_EFI_VARS` is deprecated, the current system should use `efivarfs` which is available through `CONFIG_EFIVAR_FS`. 
I think this is discruption for some users, not sure if I care.

**Comment by sgn** [comment] 2022-02-08 04:19
What is the version of `efibootmgr`?

**Comment by hervyqa** [comment] 2022-02-08 04:40
`efibootmgr-17_6`
@sgn

**Comment by hervyqa** [comment] 2022-02-08 04:57
Yesterday I've tried to create a custom iso and install it on uefi boot mode. but failed on grub installation /boot/efi.
```
Running grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=void_grub --recheck /dev/sda...
Installing for x86_64-efi platform.
EFI variables are not supported on this system.
EFI variables are not supported on this system.
grub-install: error: efibootmgr failed to register the boot entry: No such file or directory.
```

**Comment by leahneukirchen** [comment] 2022-02-08 12:54
What are your mounts there?
Can you try running `mount -t efivarfs none /sys/firmware/efi/efivars` beforehand?

**Comment by leahneukirchen** [comment] 2022-02-08 12:55
I guess this check is wrong then? `if [ -e /sys/firmware/efi/systab ]; then`

**Comment by leahneukirchen** [comment] 2022-02-08 13:02
I checked in hrmpf 5.15.11 in qemu. The check is ok, but we need the efivars mount, then efibootmgr shows stuff.

Not sure where to add this best, tho.

**Comment by leahneukirchen** [comment] 2022-02-08 15:53
I think the best way to handle this is at https://github.com/void-linux/void-runit/pull/87

**Comment by hervyqa** [comment] 2022-02-08 17:36
> What are your mounts there? Can you try running `mount -t efivarfs none /sys/firmware/efi/efivars` beforehand?

```
~ sudo mount -t efivarfs none /sys/firmware/efi/efivars
mount: /sys/firmware/efi/efivars: none already mounted or mount point busy.
```

**Comment by hervyqa** [comment] 2022-02-08 17:54
Yes. already mounted from the start, but still failed to install grub during installation.

**Comment by leahneukirchen** [comment] 2022-02-08 18:26
Does just running `efibootmgr` work? It should print a few lines of boot options or so.

**Comment by hervyqa** [comment] 2022-02-08 19:00
Yes, it's work.

```
BootCurrent: 0001
Timeout: 0 seconds
BootOrder: 0001,000
Boot0000* Void linux
Boot0001* USB Drive (UEFI) - USB
```

**Comment by leahneukirchen** [comment] 2022-02-08 19:17
Ahaaaa. The mount is not propagated into the chroot.

**Closed** 2022-02-08 19:28 UTC
