### ISSUE TITLE
void-installer: Can not use space as password for root

### ISSUE THREAD

**Issue by kotoko** [void-linux/void-mklive#225] opened 2021-11-26 08:41 UTC
I recently tried to install void in VirtualBox using generated ISO by myself. When I got to the screen with root password I typed " " (space). Later when I wanted to click "install" I saw a message that I did not set root password. I tried setting again - same message. I changed password to "a" then installer started installing.

I'm just letting you know that maybe some characters in password (space) are deleted by void-installer. I don't know if it is important. Feel free to close issue if it's irrelevant.

**Comment by camoz** [comment] 2021-12-29 11:11
That seems pretty important :)

It's probably due to how the root password is temporarily saved by the installer and then supplied to `chpasswd`: https://github.com/void-linux/void-mklive/blob/master/installer.sh.in#L662

Could also be only affecting trailing spaces, I have not looked into it further...

**Comment by paper42** [comment] 2022-01-15 15:55
duplicate of #204

**Closed by paper42** 2022-01-15 15:55 UTC
Labels: bug
