### ISSUE TITLE
dracut 056 breaks gui image building due to systemd module dependency

### ISSUE THREAD

**Issue by classabbyamp** [void-linux/void-mklive#296] opened 2022-11-17 10:18 UTC
this doesn't happen in the console images because no network manager. It works fine on dracut 053.

log highlights:
```
dracut: dracut module 'dbus-daemon' depends on 'systemd', which can't be installed
dracut: dracut module 'dbus' depends on 'dbus-daemon', which can't be installed
dracut: dracut module 'network-manager' depends on 'dbus', which can't be installed
dracut: dracut module 'network' depends on 'network-manager', which can't be installed
dracut: dracut module 'autoinstaller' depends on 'network', which can't be installed
```

<details> <summary>fuller log</summary>

```
[5/9] Generating initramfs image (xz)...
dracut: Executing: /usr/bin/dracut -N --xz --add-drivers ahci --force-add "vmklive autoinstaller" --omit systemd /boot/initrd 5.19.17_1
dracut: dracut module 'mksh' will not be installed, because command 'mksh' could not be found!
dracut: dracut module 'dbus-daemon' depends on 'systemd', which can't be installed
dracut: dracut module 'dbus' depends on 'dbus-daemon', which can't be installed
dracut: dracut module 'network-manager' depends on 'dbus', which can't be installed
dracut: dracut module 'network' depends on 'network-manager', which can't be installed
dracut: dracut module 'autoinstaller' depends on 'network', which can't be installed
dracut: dracut module 'modsign' will not be installed, because command 'keyctl' could not be found!
dracut: dracut module 'busybox' will not be installed, because command 'busybox' could not be found!
dracut: dracut module 'dbus-broker' will not be installed, because command 'dbus-broker' could not be found!
dracut: dracut module 'rngd' will not be installed, because command 'rngd' could not be found!
dracut: dracut module 'network-wicked' will not be installed, because command 'wicked' could not be found!
dracut: dracut module 'url-lib' will not be installed, because command 'curl' could not be found!
dracut: 62bluetooth: Could not find any command of '/usr/lib/bluetooth/bluetoothd /usr/libexec/bluetooth/bluetoothd'!
dracut: dracut module 'dmsquash-live-ntfs' will not be installed, because command 'ntfs-3g' could not be found!
dracut: dracut module 'multipath' will not be installed, because command 'multipath' could not be found!
dracut: dracut module 'pcsc' will not be installed, because command 'pcscd' could not be found!
dracut: dracut module 'tpm2-tss' will not be installed, because command 'tpm2' could not be found!
dracut: dracut module 'cifs' will not be installed, because command 'mount.cifs' could not be found!
dracut: dracut module 'fcoe' will not be installed, because command 'dcbtool' could not be found!
dracut: dracut module 'fcoe' will not be installed, because command 'fipvlan' could not be found!
dracut: dracut module 'fcoe' will not be installed, because command 'lldpad' could not be found!
dracut: dracut module 'fcoe' will not be installed, because command 'fcoemon' could not be found!
dracut: dracut module 'fcoe' will not be installed, because command 'fcoeadm' could not be found!
dracut: dracut module 'fcoe-uefi' will not be installed, because command 'dcbtool' could not be found!
dracut: dracut module 'fcoe-uefi' will not be installed, because command 'fipvlan' could not be found!
dracut: dracut module 'fcoe-uefi' will not be installed, because command 'lldpad' could not be found!
dracut: dracut module 'iscsi' will not be installed, because command 'iscsi-iname' could not be found!
dracut: dracut module 'iscsi' will not be installed, because command 'iscsiadm' could not be found!
dracut: dracut module 'iscsi' will not be installed, because command 'iscsid' could not be found!
dracut: dracut module 'nbd' will not be installed, because command 'nbd-client' could not be found!
dracut: 95nfs: Could not find any command of 'rpcbind portmap'!
dracut: dracut module 'nvmf' will not be installed, because command 'nvme' could not be found!
dracut: dracut module 'biosdevname' will not be installed, because command 'biosdevname' could not be found!
dracut: dracut module 'memstrack' will not be installed, because command 'memstrack' could not be found!
dracut: memstrack is not available
dracut: If you need to use rd.memdebug>=4, please install memstrack and procps-ng
dracut: dracut module 'squash' will not be installed, because command 'mksquashfs' could not be found!
dracut: dracut module 'squash' will not be installed, because command 'unsquashfs' could not be found!
dracut: dracut module 'autoinstaller' cannot be found or installed.
ERROR: Failed to generate the initramfs
```

</details>

**Comment by KF-Art** [comment] 2022-11-18 04:26
I tested it and have the same issue. Apparently the problem is NetworkManager. I tried to remove it from ISO and it built successfully. I replaced it by Connman in my custom ISOs.

**Comment by classabbyamp** [comment] 2022-11-18 04:59
well the problem is with the dbus-daemon hook wanting the systemd hook, but it's pulled in because network-manager is pulled in

**Comment by motorto** [comment] 2022-11-18 10:23
Can you try if adding this lines to the dracut.conf makes it work again ? 

```
omit_dracutmodules+=" systemd systemd-networkd "
add_dracutmodules+=" network-legacy "
```

**Comment by Vaelatern** [comment] 2022-11-18 18:39
from the linked issue, network-legacy is going away, to prefer iwd or networkmanager.

**Comment by motorto** [comment] 2022-11-21 14:34
@classabbyamp Seeing that you merged the downgrade is the plan to stay in dracut053 forever ?

**Comment by classabbyamp** [comment] 2022-11-21 15:25
we'll see

**Comment by LaszloGombos** [comment] 2022-11-23 14:53
> from the linked issue, network-legacy is going away

From what it worth, network-legacy is supported in dracut v56 and dracut v57. By supported I mean there are tests to specifically test NFS and ISCSI network boot with and without multiple NICs. The only change here is that with the v56 dracut update you need to be more specific regarding what dracut modules you want in your initramfs.

**Comment by bugcrazy** [comment] 2022-11-27 22:35
> I'll be investigating whether it's practical to switch to another initramfs generator sometime soon, but everything is back to working for now.
> 
> We've noticed the trend with dracut melding with sysd stuff too and that weighs strongly on decisions about it. at least for now, you can use xbps-alternatives to easily switch to mkinitcpio, booster, or other future initramfs generators

mkinitfs is used in Alpine, it can be easily adapted to Void.

https://gitlab.alpinelinux.org/alpine/mkinitfs

https://github.com/alpinelinux/mkinitfs

https://wiki.alpinelinux.org/wiki/Initramfs_init

https://git.alpinelinux.org/aports/tree/main/mkinitfs/APKBUILD?h=3.17-stable

**Comment by sgn** [comment] 2022-11-28 12:07
`mkinitfs` is anything but easy to be ported to other distros. Try it yourselves.

**Comment by bugcrazy** [comment] 2022-11-30 15:53
tinyramfs is portable,it's POSIX shell, no bashism. Need more features:  https://github.com/illiliti/tinyramfs/issues/7

https://github.com/illiliti/tinyramfs

**Comment by classabbyamp** [comment] 2022-11-30 16:00
if we switch, it would be to an initramfs generator that's already packaged and well-tested with void. this issue is not for bikeshedding that.

**Comment by ahesford** [comment] 2022-12-02 13:16
@abby I think we should consider this issue closed following the reversion to 053. As I noted in https://github.com/void-linux/void-mklive/pull/297#issuecomment-1335218751, the outstanding issue is not really with this project, but with our failure to identify and patch or remove incompatible modules in the Void `dracut` package.

**Closed** 2022-12-02 14:47 UTC
Labels: bug
